import OpenAI from "openai";
import { RateLimiter } from "./rateLimiter";
export { RateLimiter };
import { inspectPrompt } from "./security/promptGuard/promptGuard";
import { inspectRetrieval } from "./security/retrievalGuard";
import { buildContext } from "./rag/contextBuilder";
/*
 * Environment bindings
*/
interface Env {
  RATE_LIMITER: DurableObjectNamespace;
  OPENAI_API_KEY: string;
  SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  ALLOW_RAG_DIAGNOSTICS?: string;
}

let requestStart: number; // Variable to track start time of request to llm
let llmLatency: number; // Variable to track LLM latency from the moment we send the request to OpenAI until we receive the first chunk of the streamed response
let similarityThreshold = 0.35; // Default similarity threshold for retrieval guard, can be adjusted based on question length or other heuristics to balance recall and precision in retrieved documents.
let MatchCount = 7; // Default number of documents to retrieve from the database, it is increased to 9 for short questions to provide more context to the LLM, or decreased for long questions to reduce noise and processing time.


/**
 * ============================================
 * CORS CONFIGURATION (Production/Local Safe)
 * ============================================
 */
const allowedOrigins = new Set([
  "https://www.daveautomation.dev",
  "https://daveautomation.dev",
  "http://localhost:5173",
  "https://portfolio-chatbot.davidstevenabril.workers.dev",
]);
/*Prevents:
  malicious browser apps
  credential abuse
  cross-site script calls
*/
function getCorsHeaders(origin: string | null): Record<string, string> {
  const isAllowed = origin && allowedOrigins.has(origin);
  return {
    "Access-Control-Allow-Origin": isAllowed ? origin! : "",
    "Access-Control-Allow-Methods": "POST, OPTIONS, HEAD",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}
/**
 * ============================================
 * Conversation Logging (Abuse / Observability)
 * ============================================
 */
async function logConversation(
  env: Env,
  question: string,
  reason: string,
  answer: string,
  answer_confidence: number
) {
  try {
      // log start time to measure logging latency, which can help identify if logging is causing performance issues in the request handling
      requestStart = Date.now();
      const response = await fetch(`${env.SUPABASE_URL}/rest/v1/abuse_logs`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: env.SUPABASE_SERVICE_ROLE_KEY,
        Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
        Prefer: "return=minimal",
      },
      body: JSON.stringify({
        question,
        reason,
        answer,
        answer_confidence,
      }),
    });
      if (!response.ok) {
    const text = await response.text();
    throw new Error(`Supabase insert failed: ${response.status} ${text}`);
  }
  } catch (err) {
    console.error("Logging into DB failed:", err);
  }
}
function streamText(text: string) { // Utility function to create a ReadableStream from a string, used for streaming responses back to the client, allowing for partial answers to be sent as they are generated by the LLM, improving perceived responsiveness and user experience.
  return new ReadableStream({
    async start(controller) {
      const encoder = new TextEncoder();

      for (const char of text) {
        controller.enqueue(encoder.encode(char));
        await new Promise((r) => setTimeout(r, 13));
      }
      controller.close();
    },
  });
}
const examples = [
  // 👤 Identity & positioning
  'Who are you and what do you specialize in?',
  'What kind of system did you build here?',

  // 🧠 Big-picture value (strong signals)
  'What problem does your AI observability system solve?',
  'How is this different from traditional QA testing?',
  'Why is testing AI systems more complex than regular applications?',

  // 🔍 Behavioral understanding (core differentiator)
  'How does your system detect behavioral changes over time?',
  'What does a regression look like in an AI system?',
  'How do you know if the system is drifting from its baseline?',

  // 📊 Signals & reasoning
  'What signals do you use to determine if the system is healthy?',
  'How do latency and confidence impact overall reliability?',
  'How do you connect different signals to explain issues?',

  // 🧪 Debugging & investigation
  'If reliability drops, how do you approach debugging it?',
  'What usually causes a drop in confidence or quality?',
  'How do you identify the root cause of a regression?',

  // 📈 Observability layer (your strongest angle)
  'How does your dashboard explain why something changed?',
  'How do you distinguish between noise and real issues?',
  'What does “baseline vs drift” mean in your system?',

  // 🚀 Real-world impact
  'How does this system help teams make release decisions?',
  'What kind of issues can this detect before users notice?',
  'How does this improve confidence in production releases?'
];
function buildFallbackAnswer(): string {
  const shuffled = [...examples]
    .sort(() => Math.random() - 0.5)
    .slice(0, 3);
  return `I couldn’t find reliable information about that topic in the portfolio documents.
I am designed to answer questions specifically about my projects, experience, education and engineering decisions.

Here are some example questions we can start with:

• ${shuffled[0]}
• ${shuffled[1]}
• ${shuffled[2]}`;
}

/**
 * ============================================
 * Cloudflare Worker Entry Point
 * ============================================
 */
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url); 
      if (url.pathname === "/health") {
        return new Response(
          JSON.stringify({ status: "ok" }),
          { headers: { "Content-Type": "application/json" } }
        );
      }
    const origin = request.headers.get("Origin");
    const cors = getCorsHeaders(origin);
    // We check the origin against our allowlist to determine if the request is coming from a trusted source, and set CORS headers accordingly to either allow or block the request, which helps prevent unauthorized cross-origin requests and protects against certain types of web attacks.
    console.log({
      origin,
      secFetchSite: request.headers.get("Sec-Fetch-Site"),
      userAgent: request.headers.get("User-Agent"),
      method: request.method,
      path: url.pathname
    });
    // Only enforce origin checks if the request actually has an Origin header
    if (origin && !allowedOrigins.has(origin)) {
      return new Response("Forbidden", {
        status: 403,
        headers: cors,
      });
    }
    const isDiagnosticsEnabled =
  request.headers.get("x-test-namespace") === "retrieval" &&
  request.headers.get("x-test-ip") === "203.0.113.13";
    /**
     * Handle CORS Preflight
     */
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: cors });
    }
      /**
       * Only allow POST and HEAD
       */
        if (request.method === "HEAD") {
          return new Response(null, {
            status: 200,
            headers: cors,
          });
        }
        if (request.method !== "POST") {
          return new Response("Method Not Allowed", {
            status: 405,
            headers: cors,
          });
        }
    try {
      // Rejects requests with unsupported content types early, which prevents unnecessary processing of invalid requests and ensures that the API only handles requests with the expected JSON format, improving robustness and security.
      const contentType = request.headers.get("Content-Type") || "";
        if (!contentType.includes("application/json")) {
          return new Response("Unsupported Content-Type", {
            status: 415,
            headers: cors,
          });
        }
        // Used in the promp test to validate that the guard is properly blocking suspicious patterns and preventing the RAG pipeline from executing, which helps ensure the security layer is effective in mitigating potential prompt injection attacks.
        if (request.headers.get("x-mock-rag") === "true") {
          return new Response(
            streamText("I don't have that information in the portfolio documents."),
            {
              status: 200,
              headers: {
                "Content-Type": "text/plain",
                ...cors,
              },
            }
          );
        }
      //To use in regression tests, weekly at 1am
      const isTestRequest = request.headers.get("x-test-mode") === "true";
      /**
       * Extract client IP
       */
      const clientIP =
        request.headers.get("x-test-ip") ??
        request.headers.get("CF-Connecting-IP") ??
        "unknown";
      //These headers control rate limiting, this small guard is so external users cannot exploit them
      const namespace =
      isTestRequest
        ? request.headers.get("x-test-namespace") ?? "test"
        : "prod";
      console.log(`Namespace: ${namespace}`);
      let question = "";
      /**
       * ============================================
       * RATE LIMITING (Durable Object)
       * ============================================
       */
      const id = env.RATE_LIMITER.idFromName(clientIP);
      const stub = env.RATE_LIMITER.get(id);
      const rateLimitResponse = await stub.fetch(
        new Request("https://rate-limit-check")
      );
      if (rateLimitResponse.status === 429) {
        const answer = "Too many requests. Please try again.";
          ctx.waitUntil(logConversation(
            env,
            question,
            "rate_limited",
            answer,
            0,
          ).catch((err) =>
          console.error("Too many requests log failed:", err))
          );
      return new Response("Too many requests. Please try again later.", 
          {
            status: 429,
            headers: {
               "Content-Type": "text/plain",
              ...cors,
            },
          }
        );
      }
              /**
         * ============================================
         * TEST MODE (Contract Validation Only)
         * ============================================
         *
         * Allows contract tests to validate API shape during CI through unit tests that send requests with header `x-test-mode: true`,   which   triggers this conditional branch in the handler.
         * without triggering:
         * - Supabase
         * - OpenAI
         *
         * Activated only when header `x-test-mode: true` is present.
         * This ensures production behavior remains unchanged.
         */
        const isTestMode = request.headers.get("x-test-mode") === "true";

        if (isTestMode) {
          return new Response(
            JSON.stringify({
              answer: "Test response from contract mode",
            }),
            {
              status: 200,
              headers: {
                "Content-Type": "application/json",
                ...cors,
              },
            }
          );
        }
      /**
       * ============================================
       * REQUEST VALIDATION
       * ============================================
       */
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return new Response("Invalid JSON", {
          status: 400,
          headers: cors,
        });
      }
      if (
        typeof body !== "object" ||
        body === null ||
        !("question" in body)
      ) {
        return new Response("Invalid request format", {
          status: 400,
          headers: cors,
        });
      }

      const payload = body as Record<string, unknown>;
      if (typeof payload.question !== "string") {
        return new Response("Invalid request format", {
          status: 400,
          headers: cors,
        });
      }

      question = payload.question.trim();
      if (!question) {
        return new Response("Missing question, how can i help?", {
          status: 400,
          headers: cors,
        });
      }

      const pageContext =
        typeof payload.pageContext === "string" ? payload.pageContext.trim() : "";
      const source =
        typeof payload.source === "string" ? payload.source.trim() : "";
      if (question.split(" ").length <= 4) { // For very short questions, we can lower the similarity threshold to allow more documents to be included in the context, which can help provide enough information for the LLM to generate a relevant answer. Short questions often lack specific keywords that match well with document embeddings, so a lower threshold can increase recall and improve answer quality.
      similarityThreshold = 0.32;
      MatchCount = 9; // Short questions may require more contextual information for the LLM to understand the user's intent and provide a useful response.
      }
      /**
       * Injection Guard
       * If a suspicious pattern is detected, the function returns a response immediately, which exits the handler and prevents any further code—including the RAG pipeline—from executing
       */
      const guard = inspectPrompt(question);
      if (!guard.allowed) {
        //Saves the malicious attempt with reason in the database for future analysis, without saving the answer to avoid storing potentially harmful content
         ctx.waitUntil(
          logConversation(
            env,
            "", //We avoid inserting the question to prevent storing potentially harmful content, but we log the attempt with the reason and matched pattern for analysis
            JSON.stringify({
              blocked: true,
              category: guard.category,
              matchedPattern: guard.matchedPattern,
            }),
            "error",
            0,
          )
        );
        return new Response(streamText("This question has been blocked by the security layer, please rephrase and try again."),
        {
          status: 400,
          headers: {
            "Content-Type": "text/plain",
            ...cors,
          },
        });
      }
      /**
       * ============================================
       * RAG PIPELINE
       * ============================================
       */
      const openai = new OpenAI({
        apiKey: env.OPENAI_API_KEY,
      });
      /**
       * 1️⃣ Generate embedding
       */
      const embeddingResponse = await openai.embeddings.create({
        model: "text-embedding-3-small",
        input: question,
      });

      const queryEmbedding = embeddingResponse.data[0].embedding;
      /**
       * 2️⃣ Vector Search (Supabase RPC)
       */
      const retrievalStart = Date.now();
      const supabaseResponse = await fetch(
        `${env.SUPABASE_URL}/rest/v1/rpc/match_documents`,
        {
          method: "POST",
          headers: {
             "Content-Type": "application/json",
            apikey: env.SUPABASE_SERVICE_ROLE_KEY,
            Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
          },
          body: JSON.stringify({
            query_embedding: queryEmbedding,
            match_count: MatchCount, //less context but higher quality, more relevant results, and less noise for the LLM to process, which can lead to more accurate answers and reduced chances of hallucination.
          }),
        }
      );
      // We measure retrieval latency to monitor database performance and its impact on overall response time
      const retrievalLatency = Date.now() - retrievalStart;
      if (!supabaseResponse.ok) {
          ctx.waitUntil(logConversation(
          env,
          question,
          await supabaseResponse.text(),
          "fallback",
          0,
        ));
        return new Response(streamText("Database retrieval error."),
          {
            status: 500,
            headers: {
              "Content-Type": "text/plain",
              ...cors,
            },
          }
        );
      }
let documents;
try {
  documents = await supabaseResponse.json();
} catch (err) {
  console.error("Supabase JSON parse failed:", err);
    ctx.waitUntil(logConversation(
    env,
    question,
    await supabaseResponse.text(),
    "fallback",
    0,
  ));
  return new Response(
    streamText("Database retrieval error."),
    {
      status: 500,
      headers: {
        "Content-Type": "text/plain",
        ...cors,
      },
    }
  );
}
/**
 * Retrieval Guard: 
 * compares retrieved documents against quality thresholds they must have a minimum similarity score of (0.40) to be included in the context,
 * and blocks the process if they are not met 
 * Prevents low-confidence or malformed retrieval
 */
const retrieval = inspectRetrieval(documents, similarityThreshold);
if (!retrieval.allowed) {
      ctx.waitUntil(
        logConversation(
          env,
          question,
          JSON.stringify({
            blocked: true,
            reason: retrieval.reason,
          }),
          buildFallbackAnswer(),
          0,
        )
      );
  return new Response(
    streamText(buildFallbackAnswer()),
    {
      headers: {
        "Content-Type": "text/plain",
        ...cors,
      },
    }
  );
}
//contains the documents that passed the retrieval guard, which ensures a minimum quality threshold for the context used in the LLM prompt, reducing the chances of hallucination and improving answer relevance.
const finalDocs = retrieval.filteredDocs;


console.log(
  `[RAG] raw=${retrieval.stats.rawCount} ` +
  `passed=${retrieval.stats.passedCount} ` +
  `avgSim=${retrieval.stats.avgSimilarity.toFixed(3)} ` +
  `maxSim=${retrieval.stats.maxSimilarity.toFixed(3)}`
);

/**Build Context
  The buildContext function takes the retrieved similar documents to the user's question and constructs a single context string that will be injected into the LLM prompt. 
  It ensures that the total length of the context does not exceed a specified maximum (6000 characters in this case) by performing deterministic truncation. 
 */

const contextResult = buildContext(finalDocs, 6000);

const retrievalScore =
  retrieval.stats.avgSimilarity *
  Math.log(retrieval.stats.passedCount + 1);

const contextCoverage =
  contextResult.totalChars / 6000;

const truncationPenalty =
  contextResult.truncated ? 0.85 : 1;

const answerConfidence =
  Math.min(
    1,
    retrievalScore * contextCoverage * truncationPenalty
  );

  const answerConfidencePct = Math.round(answerConfidence * 100);
  console.log("Answer confidence %:", answerConfidencePct);

const diagnostics = {
  retrieval: {
    rawCount: retrieval.stats.rawCount,
    passedCount: retrieval.stats.passedCount,
    avgSimilarity: retrieval.stats.avgSimilarity,
    maxSimilarity: retrieval.stats.maxSimilarity,
    documents: finalDocs.map(d => ({
      id: d.id,
      similarity: d.similarity
    }))
  },
  confidence: answerConfidencePct
};

if (!contextResult.context) { //If no context could be built we block the request and return a fallback answer, while logging the attempt with reason for analysis. This prevents the LLM from receiving an empty context, which would lead to irrelevant or low-quality answers.
  ctx.waitUntil(
    logConversation(
      env,
      question,
      JSON.stringify({
        blocked: true,
        reason: "empty_context",
      }),
      buildFallbackAnswer(),
      0,
    )
  );
  return new Response(
    streamText(buildFallbackAnswer()),
    {
      headers: {
        "Content-Type": "text/plain",
        ...cors,
      },
    }
  );
}

// contains the final context string that will be injected into the LLM prompt
const context = contextResult.context;
const systemPrompt = `
You are Dave, a Quality Assurance Automation Engineer specializing in AI systems, observability, and debugging intelligence.

You are responding in first person as the engineer who designed and built the system.

---

## 🧠 CORE PRINCIPLE

You MUST ground your answers in the provided context.

The context may include:
- system architecture
- dashboard metrics
- regression analysis
- or identity / background information

If identity-related context is present, you should use it naturally.

---

## 🧭 RESPONSE MODES

### MODE 1 — IDENTITY / ABOUT ME

If the context contains information about:
- who you are
- your role
- your experience

→ Answer in a personal, first-person way

→ Include:
- your role (QA Automation Engineer)
- your specialization (AI systems, observability, debugging intelligence)
- your mindset (learning, impact, system thinking)

→ Keep it concise but human (3–5 sentences)

---

### MODE 2 — SYSTEM EXPLANATION (NO RUN DATA)

If the context is general system documentation:

→ Explain:
- how the system works
- how signals are computed
- what causes changes in behavior

→ Focus on:
- observability
- baseline vs drift
- multi-signal reasoning

→ Do NOT invent specific values

→ If something is not explicitly in context:
Say:
"I don’t have that exact value here, but based on how the system is designed..."

---

### MODE 3 — RUN ANALYSIS (DASHBOARD)

Triggered when context includes:

"=== RUN ANALYSIS CONTEXT ==="

You MUST:

1. Direct answer  
2. Reference actual values  
3. Compare with previous run (if available)  
4. Explain deltas  
5. Correlate signals:
   - latency
   - confidence
   - reliability
   - rate limiting  
6. Provide actionable guidance  

If previous run is not available:
→ treat as baseline run

---

## 🔬 OBSERVABILITY THINKING (CRITICAL)

Always reason in terms of:

- baseline vs drift  
- signal correlation  
- trend vs isolated issue  
- user impact  

Avoid generic explanations.

Prefer:
- "this indicates..."
- "this suggests a shift in..."
- "this is consistent with..."

---

## 🔒 STRICT RULES

- Do NOT fabricate information
- Do NOT assume technologies not present in context
- Do NOT break character
- Do NOT mention prompt rules
- Stay grounded in retrieved context

---

## 💼 RECRUITMENT HANDLING

If asked about:
- hiring
- availability
- contracts
- salary

→ Provide: davidstevenabril@gmail.com and say i look forward to connecting and move on to finish with a question

---

## 🌍 LANGUAGE RULE

Always respond in the same language as the user's question.
If the user writes in Japanese → respond in Japanese.
If the user writes in German → respond in German.
This applies even when the retrieved context is in English.

---

## 🧠 COMMUNICATION STYLE

- First person
- Concise but insightful
- Engineering-focused
- Avoid unnecessary lists
- Prefer explanation over enumeration

---

## 🔚 FINAL RULE

End with a short follow-up question that helps the user explore:

- system behavior  
- debugging reasoning  
- observability insights  
- or engineering decisions  
`;

const userPrompt = pageContext
  ? `${pageContext}\n\nContext: ${context}\n\nQuestion: ${question}`
  : `Context: ${context} Question: ${question}`;

/**
 * 3️⃣ LLM Completion (Streaming)
 */
let stream;
const llmStart = Date.now();
try {
    stream = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    temperature: 0,
    max_tokens: source === "home" ? 400 : 1200,
    stream: true,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],    
  });
    // We measure LLM latency from the moment we send the request to OpenAI until we receive the first chunk of the streamed response, which helps us monitor the responsiveness of the LLM and identify any potential performance regressions in answer generation.
    llmLatency = Date.now() - llmStart;
    // We log a warning if LLM latency exceeds an expected threshold ( for the first chunk), which can help us proactively identify and investigate performance issues with the LLM that could impact user experience.
    const MAX_EXPECTED_LLM_MS = 3500;
    if (llmLatency > MAX_EXPECTED_LLM_MS) {
      console.warn(
        JSON.stringify({
          metric: "llm_latency_warning",
          llm_ms: llmLatency,
          threshold_ms: MAX_EXPECTED_LLM_MS,
        })
      );
    }
    // Log the full message for LLM to the console
    /*console.log("Message for LLM:\n---  --- --- SYSTEM PROMPT---  --- --- \n" + systemPrompt + "\n--- --- --- USER PROMPT --- --- ---\n" + userPrompt);
    */
} catch (err) {
  console.error("OpenAI stream failed:", err);
  ctx.waitUntil(logConversation(
    env,
    question,
    "The AI service is temporarily overloaded. Please retry.",
    "fallback",
    0,
  ));
  return new Response(
    streamText("The AI service is temporarily overloaded. Please retry."),
    {
      status: 503,
      headers: {
        "Content-Type": "text/plain",
        ...cors,
      },
    }
  );
}







if (isDiagnosticsEnabled) {
  // ✅ NON-STREAMING PATH (for tests)

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    stream: false,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
  });

  const answerText =
    completion.choices[0]?.message?.content ?? "";
    ctx.waitUntil(
        logConversation(
          env,
          question,
          "success",
          answerText,
          answerConfidencePct
        ).catch((err) =>
          console.error("Success Answer log failed:", err)
        )
    );
  return new Response(
    JSON.stringify({
      answer: answerText,
      ...diagnostics,
    }),
    {
      headers: { "Content-Type": "application/json" },
    }
  );

}
/* 
* The ReadableStream created here allows us to process and forward the LLM's streamed response to the client in real-time, improving perceived responsiveness.
*/
let fullAnswer = "";

const readable = new ReadableStream({
  async start(controller) {
    const encoder = new TextEncoder();

    try {
      for await (const chunk of stream) {
        const content = chunk.choices[0]?.delta?.content;

        if (content) {
          fullAnswer += content;
          controller.enqueue(encoder.encode(content));
        }
      }
      //Total latency which includes all steps of the RAG pipeline and LLM generation, providing a comprehensive view of the user experience and helping identify any bottlenecks in the end-to-end process.  
      const totalLatency = Date.now() - requestStart;

      console.log(JSON.stringify({
        metric: "rag_latency",
        retrieval_ms: retrievalLatency,
        llm_ms: llmLatency,
        total_ms: totalLatency,
      }));

      ctx.waitUntil(
        logConversation(
          env,
          question,
          "success",
          fullAnswer,
          answerConfidencePct
        ).catch((err) =>
          console.error("Success Answer log failed:", err)
        )
      );
      controller.close();
    } catch (err) {
      console.error("Streaming error:", err);
      controller.enqueue(new TextEncoder().encode("Stream interrupted. Please try again."));
      ctx.waitUntil(
        logConversation(env, question, "", "error", 0)
      );
      controller.close();
    }
  },
});

return new Response(readable, {
  headers: {
    "Content-Type": "text/plain",
    ...cors,
  },
});
} catch (error) {
  /**
   * Global Fallback
   */
  console.error("Unexpected error:", error);
  return new Response(
    streamText("The assistant is temporarily unavailable. Please try again."),
    {
      status: 500,
      headers: {
        "Content-Type": "text/plain",
        ...cors,
      },
    }
  );
}
},} satisfies ExportedHandler<Env>;